### ISSUE TITLE
Getting the tsne result ?

### ISSUE THREAD

**Issue by jrabary** [saurfang/spark-tsne#2]
Hi,

I'd like to give a try to your implementation of tsne with spark. In the example you show how to write every iteration a csv file. How can we just get the final iteration result without writing it in a file ? Is it possible to not use RxScala for this algorithm ?

Best,

Jao

**Comment by saurfang** [comment]
Jao,

Thanks for the interests. The implementation isn't quite ready for prime time but you're welcome to give it a try and I'd appreciate feedback.

If you just want the final iteration result, you can instead of `foreach` here just do `toIterable.last` instead.
https://github.com/saurfang/spark-tsne/blob/master/spark-tsne-examples/src/main/scala/com/github/saurfang/spark/tsne/examples/MNIST.scala#L54

RxScala is not required as you can probably see. The motivation is that I don't want to accumulate the history and return them all together because each individual mapping is very large and cannot be easily parallelized. However as you can see from the visualization, I think the optimization history is very interesting and may point to potential tweaking ideas.

I have very little experience in RxScala but that was the first thing came in my mind. Alternatively I suppose we can take a callback function instead. I might actually give this a try this weekend and axe the RxScala altogether this weekend.
FYI, I found about the solution of `last` here: https://github.com/kevinwright/RxScala/blob/master/src/main/scala/rxscala/observables/BlockingObservable.scala#L55

**Comment by jrabary** [comment]
Thank you for your reply. The last solution returns an Obsevable object. How do you get the value of the Y inside this object. Sorry for this stupid question but I never use RxScala :)

**Comment by saurfang** [comment]
No worries. What I meant is that this will give you the final `DenseMatrix[Double]`.

``` scala
BHTSNE.tsne(pcaMatrix, maxIterations = 500).toBlocking.toIterable.last._2
```

(Using `BHTSNE` as an example here)

**Comment by saurfang** [comment]
FYI. I dropped Rx and use callback function instead. The tsne function itself returns the final matrix so if you don't care about the intermediate results don't bother to pass a callback function.

**Comment by jrabary** [comment]
Thank you for the help. Having the intermediate results would be interesting for debug purpose. This could be an option for every iterative algortihm such as SDG. May be we can ask spark developers how they would handle this right inside spark ?
